### ISSUE TITLE
Why is -fobject-code enabled by default?

### ISSUE THREAD

**Issue by mpickering** [dramforever/vscode-ghc-simple#36]
I would have expected that the default flags would have been `-fno-code` and `-fwrite-interface-files`, maybe also setting the `-hidir` so the correct directory isn't polluted. Using `-fobject-code` and `-fbyte-code` by default will slow down reloads by a lot.

**Comment by dramforever** [comment]
I got this advice from <https://chrisdone.com/posts/making-ghci-fast/>. In fact by default I implemented this too:

> After that, you may notice that loading some modules gives less type information and general metadata than before. For that, re-enable byte-compilation temporarily with `-fbyte-code` (`:set -fbyte-code`) and `:load` that module again, you now have fast recompilation with complete information, too.

With regards to `-fno-code`:

> Another tip is to use `-fno-code` to have really fast compilation. This also works in combination with `-fobject-code`. But I’d recommend using this only for type checking, not for getting useful warnings (like pattern match inexhaustiveness). So I would combine it with -fobject-code in the same way as above with `-fbyte-code`, and then once you’re done hacking, re-enable `-fobject-code` and rebuild everything.

In my experience these are still true. Are they not anymore?

Also, I'd like to have the inline REPL feature enabled by default, and `-fno-code` does not running expressions, so that's a no for me.

**Comment by dramforever** [comment]
Fix upcoming 3413fdd9f6ef2dbfb80a79a93601eaf103db52b5. Forgot to put issue number in commit message.

**Comment by dramforever** [comment]
No longer :smile_cat:
