### ISSUE TITLE
GHC simple not loading

### ISSUE THREAD

**Issue by SUPERNOOB20** [dramforever/vscode-ghc-simple#94]
## Status

- [ ] A workaround is available
- [ ] A fix is written
- [ ] A fix is released
- [ ] The fixed version is on the marketplace.

---

- Version of vscode-ghc-simple: 0.2.3
- Version of VSCode: 1.57.0
- Version of Haskell-related tools: None
    
    - GHC: Yes.
    - Stack: No.
    - Cabal: No.

## Steps to reproduce

- Have the GHC simple extension already installed.
- Open a file or have one already opened.
- This message error should appear stating the extension failed to load:
    - [https://imgur.com/uurOk80](url)

## Workspace

I have nothing settled up, I would believe.

## GHC log

ghci | RedownloadInvalidResponse Request {
ghci |   host                 = "raw.githubusercontent.com"
ghci |   port                 = 443
ghci |   secure               = True
ghci |   requestHeaders       = []
ghci |   path                 = "/fpco/lts-haskell/master//lts-17.15.yaml"
ghci |   queryString          = ""
ghci |   method               = "GET"
ghci |   proxy                = Nothing
ghci |   rawBody              = False
ghci |   redirectCount        = 10
ghci |   responseTimeout      = ResponseTimeoutDefault
ghci |   requestVersion       = HTTP/1.1
ghci | }
ghci |  "C:\\sr\\build-plan\\lts-17.15.yaml" (Response {responseStatus = Status {statusCode = 404, statusMessage = "Not Found"}, responseVersion = HTTP/1.1, responseHeaders = [("Connection","keep-alive"),("Content-Length","14"),("Content-Security-Policy","default-src 'none'; style-src 'unsafe-inline'; sandbox"),("Strict-Transport-Security","max-age=31536000"),("X-Content-Type-Options","nosniff"),("X-Frame-Options","deny"),("X-XSS-Protection","1; mode=block"),("Content-Type","text/plain; charset=utf-8"),("X-GitHub-Request-Id","E9A4:1691:7E8874:A1C323:60C3AEAB"),("Accept-Ranges","bytes"),("Date","Fri, 11 Jun 2021 18:42:51 GMT"),("Via","1.1 varnish"),("X-Served-By","cache-cgh11181-CGH"),("X-Cache","HIT"),("X-Cache-Hits","1"),("X-Timer","S1623436972.697785,VS0,VE175"),("Vary","Authorization,Accept-Encoding"),("Access-Control-Allow-Origin","*"),("X-Fastly-Request-ID","af83d0210baa056180dec0afd151e374f26f8418"),("Expires","Fri, 11 Jun 2021 18:47:51 GMT"),("Source-Age","0")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose})

Also this will show up in VS Code Log (Extension Host):
[2021-06-11 15:34:19.097] [exthost] [error] [dramforever.vscode-ghc-simple] provider FAILED

**Comment by dramforever** [comment]
The log shows that you do have Stack installed. Without further configuration, the extension has to pick one way to start GHCi, and it prefers using `stack` over `ghci`. Unfortunately Stack isn't working, apparently due to a network error (as seen in the logs).

You can set the `ghcSimple.replCommand` setting to `ghci` to force the extension to use just `ghci` if that's what you wanted. Check the project wiki for details. For example: https://github.com/dramforever/vscode-ghc-simple/wiki/Project-Configuration#legacy-configuration-replcommand or https://github.com/dramforever/vscode-ghc-simple/wiki/Extension-Configuration

If that doesn't work then it's probably #76
